services:

  prometheus:
    image: prom/prometheus:v2.33.5
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    networks:
      - default

  node-exporter:
    image: prom/node-exporter:v1.3.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: exporter
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    networks:
      - default

  grafana:
    image: grafana/grafana:8.5.2
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    networks:
      - default

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-7.0.10
    container_name: zabbix-server
    depends_on:
      - mysql
    environment:
      TZ: ${TZ}
      DB_SERVER_HOST: "mysql"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: ${ZABBIX_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ZABBIX_MYSQL_PASSWORD_ROOT}
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    user: root
    networks:
      - default
    restart: always

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-7.0.10
    container_name: zabbix-web
    depends_on:
      - mysql
      - zabbix-server
    environment:
      TZ: ${TZ}
      DB_SERVER_HOST: "mysql"
      ZBX_SERVER_HOST: "zabbix-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: ${ZABBIX_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ZABBIX_MYSQL_PASSWORD_ROOT}  
    volumes:
      - ./zabbix/graphfont.ttf:/usr/share/zabbix/fonts/graphfont.ttf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
    user: root
    networks:
      - default
    restart: always 

  mysql:
    image: mysql:8.4.4
    container_name: zabbix-mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      TZ: ${TZ}
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: ${ZABBIX_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ZABBIX_MYSQL_PASSWORD_ROOT}     
    networks:
      - default
    volumes:
      - ./zabbix/database/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: always

  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb_container
    restart: always
    ports:
      - 8086:8086
      - 8089:8089/udp
    volumes:
      - ./influxdb:/var/lib/influxdb
    networks:
      - default

  graphite:
    image: graphiteapp/graphite-statsd:1.1.8-3
    container_name: graphite
    restart: always
    ports:
      - 8081:8080
      - 2003:2003
    networks:
      - default

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
